name: CI/CD
# 触发条件为 push
on:
  push:
    branches:
      - master
    # 修改文件范围, 不在范围内不触发
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
      - '**/**'
# 任务
jobs:
  test:
    # 运行的环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: 打包镜像, 上传 Docker Hub
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build --platform linux/amd64 -t fe-image:latest  .
          docker tag fe-image:latest ${{ secrets.DOCKER_REPOSITORY }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}

      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          # 执行脚本
          # 可以配置为一个deploy.sh文件，但是我遇到了权限问题，所以就手写在这里了
          script: |
            docker pull 1440054388/fe-image:latest
            docker stop fe-container
            docker rm fe-container
            docker run -itd -p 8081:80 --name fe-container 1440054388/fe-image:latest
            docker image prune -f
            docker container prune -f